### ISSUE TITLE
Example of what put on each options please?

### ISSUE THREAD

**Issue by ZeroCool22** [notorioushaze/BlessINI#1]
Like title say, can you include a image of what value to put on each option? Thx!

For ex: I f it's a number or True/False, etc..

**Comment by MeltedPixel** [comment]
Hey @ZeroCool22,

This actually already exists it just wasn't clear. If you hover over the nameplates it has a description of what the option does (some of them) and the community recommended option. I also just released a new version that makes it a little more clear that those are already implemented.
